create TABLESPACE ts_finance 
DATAFILE 'ts_finance.dbf' 
SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

ALTER TABLE TBL_SALARIES MOVE TABLESPACE TS_FINANCE;
ALTER TABLE TBL_ACCOUNT MOVE TABLESPACE TS_FINANCE;
ALTER TABLE TBL_COMISSIONS MOVE TABLESPACE TS_FINANCE;
ALTER TABLE TBL_SPECIALITIES MOVE TABLESPACE TS_FINANCE;
ALTER TABLE TBL_AGRONOMISTS MOVE TABLESPACE TS_FINANCE;