-- TBL_SALARIES
CREATE INDEX IDX_SAL_AMOUNT ON TBL_SALARIES(sal_amount) TABLESPACE TS_FINANCE;

-- TBL_ACCOUNT
CREATE INDEX IDX_ACC_STATE ON TBL_ACCOUNT(acc_state) TABLESPACE TS_FINANCE;
CREATE INDEX IDX_ACC_DATE ON TBL_ACCOUNT(acc_date) TABLESPACE TS_FINANCE;

-- TBL_COMISSIONS
CREATE INDEX IDX_COM_AGRONOMIST ON TBL_COMISSIONS(com_agronomist_id) TABLESPACE TS_FINANCE;
CREATE INDEX IDX_COM_DATE ON TBL_COMISSIONS(com_date) TABLESPACE TS_FINANCE;
CREATE INDEX IDX_COM_AMOUNT ON TBL_COMISSIONS(com_amount) TABLESPACE TS_FINANCE;

-- TBL_SPECIALITIES
CREATE INDEX IDX_SPE_PRICE ON TBL_SPECIALITIES(spe_price) TABLESPACE TS_FINANCE;
CREATE INDEX IDX_SPE_TYPE ON TBL_SPECIALITIES(spe_type) TABLESPACE TS_FINANCE;

-- TBL_AGRONOMISTS
CREATE INDEX IDX_AGR_SALARY ON TBL_AGRONOMISTS(agr_salary_id) TABLESPACE TS_FINANCE;
CREATE INDEX IDX_AGR_CONSULT_PRICE ON TBL_AGRONOMISTS(agr_consult_price) TABLESPACE TS_FINANCE;