-- =========================================
-- Las llaves primarias deben de ser numeros consecutivos e incluirlo de forma
-- automatica por cada registro insertado.
-- =========================================
CREATE SEQUENCE SEQ_TBL_VISITS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TBL_VISITS_AI
BEFORE INSERT ON TBL_VISITS
FOR EACH ROW
BEGIN
    IF :NEW.vis_id IS NULL THEN
        SELECT SEQ_TBL_VISITS.NEXTVAL
        INTO :NEW.vis_id
        FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE SEQ_TBL_CANCELLED_HISTORIES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TBL_CANCELLED_HISTORIES_AI
BEFORE INSERT ON TBL_CANCELLED_HISTORIES
FOR EACH ROW
BEGIN
    IF :NEW.cah_id IS NULL THEN
        SELECT SEQ_TBL_CANCELLED_HISTORIES.NEXTVAL
        INTO :NEW.cah_id
        FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE SEQ_TBL_AVAILABILITIES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TBL_AVAILABILITIES_AI
BEFORE INSERT ON TBL_AVAILABILITIES
FOR EACH ROW
BEGIN
    IF :NEW.ava_id IS NULL THEN
        SELECT SEQ_TBL_AVAILABILITIES.NEXTVAL
        INTO :NEW.ava_id
        FROM DUAL;
    END IF;
END;
/

CREATE SEQUENCE SEQ_TBL_PRODUCERS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TBL_PRODUCERS_AI
BEFORE INSERT ON TBL_PRODUCERS
FOR EACH ROW
BEGIN
    IF :NEW.pro_id IS NULL THEN
        SELECT SEQ_TBL_PRODUCERS.NEXTVAL
        INTO :NEW.pro_id
        FROM DUAL;
    END IF;
END;
/

-- MISMA IDEA PARA TODAS LAS TABLAS...