CREATE TABLESPACE TS_LOGS_DATA
DATAFILE 'TS_LOGS_DATA.dbf'
SIZE 500M
AUTOEXTEND ON NEXT 100M
MAXSIZE UNLIMITED
ONLINE;

-- Mover LOG_AGRONOMIC_VISITS
ALTER TABLE LOG_AGRONOMIC_VISITS MOVE TABLESPACE TS_LOGS_DATA;

-- Mover LOG_AVAILABILITY_CHANGES
ALTER TABLE LOG_AVAILABILITY_CHANGES MOVE TABLESPACE TS_LOGS_DATA;

-- Mover LOG_FIELD_INSPECTIONS
ALTER TABLE LOG_FIELD_INSPECTIONS MOVE TABLESPACE TS_LOGS_DATA;

-- Mover LOG_LABORATORY_ANALYSIS
ALTER TABLE LOG_LABORATORY_ANALYSIS MOVE TABLESPACE TS_LOGS_DATA;

-- Mover LOG_CROP_HISTORY
ALTER TABLE LOG_CROP_HISTORY MOVE TABLESPACE TS_LOGS_DATA;

-- Mover LOG_APPLIED_TREATMENTS
ALTER TABLE LOG_APPLIED_TREATMENTS MOVE TABLESPACE TS_LOGS_DATA;

-- Mover LOG_AGRONOMIST_CHANGES
ALTER TABLE LOG_AGRONOMIST_CHANGES MOVE TABLESPACE TS_LOGS_DATA;

-- Mover LOG_SYSTEM_ERRORS
ALTER TABLE LOG_SYSTEM_ERRORS MOVE TABLESPACE TS_LOGS_DATA;

-- Mover LOG_DATA_MODIFICATIONS
ALTER TABLE LOG_DATA_MODIFICATIONS MOVE TABLESPACE TS_LOGS_DATA;

-- Mover las nuevas tablas financieras
ALTER TABLE LOG_FINANCIAL_TRANSACTIONS MOVE TABLESPACE TS_LOGS_DATA;
ALTER TABLE LOG_ACCOUNT_PAYMENTS MOVE TABLESPACE TS_LOGS_DATA;
ALTER TABLE LOG_COMMISSIONS MOVE TABLESPACE TS_LOGS_DATA;
ALTER TABLE LOG_AGRONOMIST_FINANCIAL MOVE TABLESPACE TS_LOGS_DATA;
ALTER TABLE LOG_SPECIALTY_PRICING MOVE TABLESPACE TS_LOGS_DATA;
ALTER TABLE LOG_SALARY_CHANGES MOVE TABLESPACE TS_LOGS_DATA;