-- TBL_DISEASES
CREATE INDEX IDX_DIS_NAME ON TBL_DISEASES(dis_name) TABLESPACE TS_PESTS_TREATMENTS;
CREATE INDEX IDX_DIS_SEVERITY ON TBL_DISEASES(dis_severity) TABLESPACE TS_PESTS_TREATMENTS;

-- TBL_PESTS
CREATE INDEX IDX_PES_NAME ON TBL_PESTS(pes_name) TABLESPACE TS_PESTS_TREATMENTS;
CREATE INDEX IDX_PES_SEVERITY ON TBL_PESTS(pes_severity) TABLESPACE TS_PESTS_TREATMENTS;

-- TBL_TREATMENTS
CREATE INDEX IDX_TRE_NAME ON TBL_TREATMENTS(tre_name) TABLESPACE TS_PESTS_TREATMENTS;
CREATE INDEX IDX_TRE_TYPE ON TBL_TREATMENTS(tre_treatment_type_id) TABLESPACE TS_PESTS_TREATMENTS;

-- TBL_TREATMENTS_TYPE
CREATE INDEX IDX_TRT_NAME ON TBL_TREATMENTS_TYPE(trt_name) TABLESPACE TS_PESTS_TREATMENTS;