CREATE TABLESPACE TS_PESTS_TREATMENTS
DATAFILE 'TS_PESTS_TREATMENTS.dbf' SIZE 200M
AUTOEXTEND ON NEXT 100M MAXSIZE 2G;

ALTER TABLE TBL_DISEASES MOVE TABLESPACE TS_PESTS_TREATMENTS;
ALTER TABLE TBL_PESTS MOVE TABLESPACE TS_PESTS_TREATMENTS;
ALTER TABLE TBL_TREATMENTS MOVE TABLESPACE TS_PESTS_TREATMENTS;
ALTER TABLE TBL_TREATMENTS_TYPE MOVE TABLESPACE TS_PESTS_TREATMENTS;
ALTER TABLE TBL_FAR_X_DIS MOVE TABLESPACE TS_PESTS_TREATMENTS;
ALTER TABLE TBL_FARM_X_PESTS MOVE TABLESPACE TS_PESTS_TREATMENTS;
ALTER TABLE TBL_TEF_X_TRE MOVE TABLESPACE TS_PESTS_TREATMENTS;