CREATE TABLE TBL_ROLE_LOGBOOK (
    log_id NUMBER PRIMARY KEY,
    role_name VARCHAR2(30) NOT NULL,
    username VARCHAR2(30) NOT NULL,
    action_type VARCHAR2(20) NOT NULL, -- 'LOGIN_SUCCESS', 'LOGIN_FAILED', 'PASSWORD_CHANGE', 'ROLE_ENABLED', 'ROLE_DISABLED'
    action_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    ip_address VARCHAR2(45),
    session_id VARCHAR2(100),
    details VARCHAR2(4000)
) TABLESPACE TS_MASTER_DATA;

CREATE SEQUENCE role_logbook_seq START WITH 1 INCREMENT BY 1;

-- Índices para mejor performance
CREATE INDEX IDX_ROLE_LOG_ROLE ON TBL_ROLE_LOGBOOK(role_name) TABLESPACE TS_MASTER_DATA;
CREATE INDEX IDX_ROLE_LOG_DATE ON TBL_ROLE_LOGBOOK(action_date) TABLESPACE TS_MASTER_DATA;
CREATE INDEX IDX_ROLE_LOG_USER ON TBL_ROLE_LOGBOOK(username) TABLESPACE TS_MASTER_DATA;