CREATE TABLE TBL_ROLE_LOGBOOK (
    log_id NUMBER PRIMARY KEY,
    role_name VARCHAR2(30) NOT NULL,
    username VARCHAR2(30) NOT NULL,
    action_type VARCHAR2(20) NOT NULL, -- 'LOGIN_SUCCESS', 'LOGIN_FAILED', 'PASSWORD_CHANGE', 'ROLE_ENABLED', 'ROLE_DISABLED'
    action_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    ip_address VARCHAR2(45),
    session_id VARCHAR2(100),
    details VARCHAR2(4000)
);

CREATE SEQUENCE role_logbook_seq START WITH 1 INCREMENT BY 1;