CREATE TABLESPACE ts_agricultural_operations
DATAFILE 'ts_agricultural_operations.dbf' SIZE 500M
AUTOEXTEND ON NEXT 200M MAXSIZE 8G;

ALTER TABLE TBL_FARMS MOVE TABLESPACE TS_AGRICULTURAL_OPERATIONS;
ALTER TABLE TBL_CROPS MOVE TABLESPACE TS_AGRICULTURAL_OPERATIONS;
ALTER TABLE TBL_CROPS_TYPE MOVE TABLESPACE TS_AGRICULTURAL_OPERATIONS;
ALTER TABLE TBL_FIELD_INSPECTIONS MOVE TABLESPACE TS_AGRICULTURAL_OPERATIONS;
ALTER TABLE TBL_HISTORY_CROPS MOVE TABLESPACE TS_AGRICULTURAL_OPERATIONS;
ALTER TABLE TBL_PRODUCERS MOVE TABLESPACE TS_AGRICULTURAL_OPERATIONS;
ALTER TABLE TBL_FAR_X_CRO MOVE TABLESPACE TS_AGRICULTURAL_OPERATIONS;