-- TBL_FARMS
CREATE INDEX IDX_FAR_COMPANY ON TBL_FARMS(far_company_id) TABLESPACE TS_AGRICULTURAL_OPERATIONS;
CREATE INDEX IDX_FAR_HECTARES ON TBL_FARMS(far_hectares) TABLESPACE TS_AGRICULTURAL_OPERATIONS;
CREATE INDEX IDX_FAR_REGISTER_DATE ON TBL_FARMS(far_register_date) TABLESPACE TS_AGRICULTURAL_OPERATIONS;

-- TBL_CROPS
CREATE INDEX IDX_CRO_AGE ON TBL_CROPS(cro_age) TABLESPACE TS_AGRICULTURAL_OPERATIONS;
CREATE INDEX IDX_CRO_AREA ON TBL_CROPS(cro_area) TABLESPACE TS_AGRICULTURAL_OPERATIONS;

-- TBL_CROPS_TYPE
CREATE INDEX IDX_CRT_TYPE ON TBL_CROPS_TYPE(crt_type) TABLESPACE TS_AGRICULTURAL_OPERATIONS;

-- TBL_FIELD_INSPECTIONS
CREATE INDEX IDX_FII_CROPS ON TBL_FIELD_INSPECTIONS(fii_crops_id) TABLESPACE TS_AGRICULTURAL_OPERATIONS;
CREATE INDEX IDX_FII_AGRONOMISTS ON TBL_FIELD_INSPECTIONS(fii_agronomists_id) TABLESPACE TS_AGRICULTURAL_OPERATIONS;
CREATE INDEX IDX_FII_DATE ON TBL_FIELD_INSPECTIONS(fii_ambient_temperature) TABLESPACE TS_AGRICULTURAL_OPERATIONS;

-- TBL_HISTORY_CROPS
CREATE INDEX IDX_HIC_FARM ON TBL_HISTORY_CROPS(hic_farm_id) TABLESPACE TS_AGRICULTURAL_OPERATIONS;
CREATE INDEX IDX_HIC_SOWING_DATE ON TBL_HISTORY_CROPS(hic_sowing_date) TABLESPACE TS_AGRICULTURAL_OPERATIONS;
CREATE INDEX IDX_HIC_HARVEST_DATE ON TBL_HISTORY_CROPS(hic_harvest_date) TABLESPACE TS_AGRICULTURAL_OPERATIONS;

-- TBL_PRODUCERS
CREATE INDEX IDX_PRO_PERSON ON TBL_PRODUCERS(pro_person_id) TABLESPACE TS_AGRICULTURAL_OPERATIONS;
CREATE INDEX IDX_PRO_OCUPATION ON TBL_PRODUCERS(pro_ocupation_id) TABLESPACE TS_AGRICULTURAL_OPERATIONS;
CREATE INDEX IDX_PRO_REG_DATE ON TBL_PRODUCERS(pro_registration_date) TABLESPACE TS_AGRICULTURAL_OPERATIONS;
CREATE INDEX IDX_PRO_ACTIVE ON TBL_PRODUCERS(pro_active) TABLESPACE TS_AGRICULTURAL_OPERATIONS;