--! Basic Role
CREATE ROLE basic;
GRANT CONNECT TO basic;
GRANT CREATE SESSION TO basic;

--! Manager Role
CREATE ROLE manager;
GRANT basic TO manager;
GRANT CREATE TABLE TO manager;
GRANT CREATE VIEW TO manager;
GRANT CREATE PROCEDURE TO manager;
GRANT CREATE SEQUENCE TO manager;
GRANT CREATE TRIGGER TO manager;
GRANT CREATE TYPE TO manager;
GRANT CREATE TABLESPACE TO manager;

--! Agronomist Role
CREATE ROLE agronomist;
GRANT basic TO agronomist;

-- Principal permissions for agronomist role (Agricultural Operations)
GRANT SELECT, INSERT, UPDATE ON TBL_FIELD_INSPECTIONS TO agronomist;
GRANT SELECT, INSERT, UPDATE ON TBL_ANOTATIONS TO agronomist;
GRANT SELECT, INSERT, UPDATE ON TBL_TECHNICAL_FILES TO agronomist;
GRANT SELECT, INSERT, UPDATE ON TBL_ENVIRONMENTALS_DATA TO agronomist;
GRANT SELECT, INSERT, UPDATE ON TBL_LABORATORY_ANALYSIS TO agronomist;

-- Only read permissions for agronomist role
GRANT SELECT ON TBL_CROPS TO agronomist;
GRANT SELECT ON TBL_CROPS_TYPE TO agronomist;
GRANT SELECT ON TBL_DISEASES TO agronomist;
GRANT SELECT ON TBL_PESTS TO agronomist;
GRANT SELECT ON TBL_TREATMENTS TO agronomist;
GRANT SELECT ON TBL_TREATMENTS_TYPE TO agronomist;
GRANT SELECT ON TBL_FARMS TO agronomist;
GRANT SELECT ON TBL_PRODUCERS TO agronomist;

-- Agenda management permissions (Scheduling Appointments)
GRANT SELECT, INSERT, UPDATE ON TBL_SCHEDULE_AGRONOMISTS TO agronomist;
GRANT SELECT, INSERT, UPDATE ON TBL_AVAILABILITIES TO agronomist;
GRANT SELECT, INSERT, UPDATE ON TBL_VISITS TO agronomist;

--! Technical Role
CREATE ROLE technical;
GRANT basic TO technical;

-- Technical data management permissions (Technical Environmental)
GRANT SELECT, INSERT, UPDATE ON TBL_TECHNICAL_FILES TO technical;
GRANT SELECT, INSERT, UPDATE ON TBL_ENVIRONMENTALS_DATA TO technical;
GRANT SELECT, INSERT, UPDATE ON TBL_CLIMATIC_CONDITIONS TO technical;
GRANT SELECT, INSERT, UPDATE ON TBL_SOILS_TYPE TO technical;
GRANT SELECT, INSERT, UPDATE ON TBL_WATER_SOURCES TO technical;
GRANT SELECT, INSERT, UPDATE ON TBL_LABORATORY_ANALYSIS TO technical;
GRANT SELECT, INSERT, UPDATE ON TBL_FIELD_INSPECTIONS TO technical;

-- Only read permissions for technical role
GRANT SELECT ON TBL_CROPS TO technical;
GRANT SELECT ON TBL_FARMS TO technical;
GRANT SELECT ON TBL_SOILS TO technical;

--! Secretary Role
CREATE ROLE secretary;
GRANT basic TO secretary;

-- Contact and scheduling management permissions
GRANT SELECT, INSERT, UPDATE ON TBL_PERSON TO secretary;
GRANT SELECT, INSERT, UPDATE ON TBL_CONTACTS TO secretary;
GRANT SELECT, INSERT, UPDATE ON TBL_COMPANIES TO secretary;
GRANT SELECT, INSERT, UPDATE ON TBL_CON_X_COM TO secretary;
GRANT SELECT, INSERT, UPDATE ON TBL_PER_X_CON TO secretary;

-- Agenda management permissions (Scheduling Appointments)
GRANT SELECT, INSERT, UPDATE ON TBL_SCHEDULE_AGRONOMISTS TO secretary;
GRANT SELECT, INSERT, UPDATE ON TBL_SCHEDULE_SPECIALITIES TO secretary;
GRANT SELECT, INSERT, UPDATE ON TBL_AVAILABILITIES TO secretary;
GRANT SELECT, INSERT, UPDATE ON TBL_VISITS TO secretary;
GRANT SELECT, INSERT, UPDATE ON TBL_CANCELLED_HISTORIES TO secretary;

-- Only read permissions for secretary role
GRANT SELECT ON TBL_AGRONOMISTS TO secretary;
GRANT SELECT ON TBL_SPECIALITIES TO secretary;
GRANT SELECT ON TBL_FARMS TO secretary;
GRANT SELECT ON TBL_PRODUCERS TO secretary;