-- SYSBDA's
create user reds IDENTIFIED by reds;
grant sys to reds;
grant basic to reds;

create user fabiux IDENTIFIED by fabiux;
grant sys to fabiux;
grant basic to fabiux;

create user yzma IDENTIFIED by yzma;
grant sys to yzma;
grant basic to yzma;

--! Agronomist user example
CREATE USER agronomist_maria IDENTIFIED BY "@groSecure2024!"
PROFILE agronomist_profile
DEFAULT TABLESPACE TS_AGRICULTURAL_OPERATIONS
TEMPORARY TABLESPACE temp
QUOTA 200M ON TS_AGRICULTURAL_OPERATIONS
QUOTA 100M ON TS_SCHEDULING_APPOINTMENTS
QUOTA 100M ON TS_TECHNICAL_ENVIRONMENTAL;

GRANT agronomist TO agronomist_maria;

--! Technical user example
CREATE USER tech_carlos IDENTIFIED BY "TechAn@lyst2024!"
PROFILE technical_profile
DEFAULT TABLESPACE TS_TECHNICAL_ENVIRONMENTAL
TEMPORARY TABLESPACE temp
QUOTA 300M ON TS_TECHNICAL_ENVIRONMENTAL
QUOTA 100M ON TS_AGRICULTURAL_OPERATIONS
QUOTA 100M ON TS_PESTS_TREATMENTS;

GRANT technical TO tech_carlos;

--! Secretary user example
CREATE USER secretary_ana IDENTIFIED BY "@dminSecure2024!"
PROFILE secretary_profile
DEFAULT TABLESPACE TS_SCHEDULING_APPOINTMENTS
TEMPORARY TABLESPACE temp
QUOTA 150M ON TS_SCHEDULING_APPOINTMENTS
QUOTA 50M ON TS_MASTER_DATA
QUOTA 50M ON TS_CATALOGS;

GRANT secretary TO secretary_ana;

--! Manager user example
CREATE USER db_manager IDENTIFIED BY "Man@gerSecure2024!"
PROFILE manager_profile
DEFAULT TABLESPACE TS_FINANCE
TEMPORARY TABLESPACE temp
QUOTA unlimited ON TS_FINANCE
QUOTA unlimited ON TS_MASTER_DATA
QUOTA unlimited ON TS_AGRICULTURAL_OPERATIONS
QUOTA unlimited ON TS_TECHNICAL_ENVIRONMENTAL
QUOTA unlimited ON TS_PESTS_TREATMENTS
QUOTA unlimited ON TS_SCHEDULING_APPOINTMENTS
QUOTA unlimited ON TS_CATALOGS;

GRANT manager TO db_manager;