PROMPT 8.1 Configurando ACL...
@&BASE_PATH/Notifications/acl_config/create-acl.sql

PROMPT 8.2 Verificando configuración...
@&BASE_PATH/Notifications/acl_config/verify.sql

PROMPT 5.6 Package de Seguridad...
@&BASE_PATH/security/encryted_role/package/header.pks
@&BASE_PATH/security/encryted_role/package/body.pkb

PROMPT 7.7 Trigger: ENCRYPTED_ROLE...
@&BASE_PATH/security/logbooks/encryted_role/trigger.sql