-- TBL_PERSON
CREATE INDEX IDX_PER_LASTNAME ON TBL_PERSON(per_lastname) TABLESPACE TS_MASTER_DATA;
CREATE INDEX IDX_PER_IDENTIFICATION ON TBL_PERSON(per_identification) TABLESPACE TS_MASTER_DATA;
CREATE INDEX IDX_PER_BIRTHDAY ON TBL_PERSON(per_birthday) TABLESPACE TS_MASTER_DATA;
CREATE INDEX IDX_PER_NATIONALITY ON TBL_PERSON(per_nationality_id) TABLESPACE TS_MASTER_DATA;
CREATE INDEX IDX_PER_GENDER ON TBL_PERSON(per_gender) TABLESPACE TS_MASTER_DATA;

-- TBL_ADDRESS
CREATE INDEX IDX_ADD_COUNTRY ON TBL_ADDRESS(add_country) TABLESPACE TS_MASTER_DATA;
CREATE INDEX IDX_ADD_PROVINCE ON TBL_ADDRESS(add_province) TABLESPACE TS_MASTER_DATA;
CREATE INDEX IDX_ADD_CANTON ON TBL_ADDRESS(add_canton) TABLESPACE TS_MASTER_DATA;

-- TBL_COMPANIES
CREATE INDEX IDX_COM_NAME ON TBL_COMPANIES(com_name) TABLESPACE TS_MASTER_DATA;
CREATE INDEX IDX_COM_OWNER ON TBL_COMPANIES(com_owner_id) TABLESPACE TS_MASTER_DATA;
CREATE INDEX IDX_COM_FOUNDATION ON TBL_COMPANIES(com_foundation_date) TABLESPACE TS_MASTER_DATA;

-- TBL_CONTACTS
CREATE INDEX IDX_CON_TYPE ON TBL_CONTACTS(con_type) TABLESPACE TS_MASTER_DATA;
CREATE INDEX IDX_CON_CONTACT ON TBL_CONTACTS(con_contact) TABLESPACE TS_MASTER_DATA;