CREATE TABLESPACE ts_master_data
DATAFILE 'ts_master_data.dbf' SIZE 200M
AUTOEXTEND ON NEXT 100M MAXSIZE 4G;

ALTER TABLE TBL_PERSON MOVE TABLESPACE TS_MASTER_DATA;
ALTER TABLE TBL_ADDRESS MOVE TABLESPACE TS_MASTER_DATA;
ALTER TABLE TBL_COMPANIES MOVE TABLESPACE TS_MASTER_DATA;
ALTER TABLE TBL_CONTACTS MOVE TABLESPACE TS_MASTER_DATA;
ALTER TABLE TBL_NACIONALITIES MOVE TABLESPACE TS_MASTER_DATA;
ALTER TABLE TBL_OCUPATIONS MOVE TABLESPACE TS_MASTER_DATA;
ALTER TABLE TBL_CERTFICATIONS MOVE TABLESPACE TS_MASTER_DATA;