CREATE TABLESPACE TS_SCHEDULING_APPOINTMENTS
DATAFILE 'TS_SCHEDULING_APPOINTMENTS.dbf' SIZE 150M
AUTOEXTEND ON NEXT 50M MAXSIZE 2G;

ALTER TABLE TBL_SCHEDULE_AGRONOMISTS MOVE TABLESPACE TS_SCHEDULING_APPOINTMENTS;
ALTER TABLE TBL_SCHEDULE_SPECIALITIES MOVE TABLESPACE TS_SCHEDULING_APPOINTMENTS;
ALTER TABLE TBL_AVAILABILITIES MOVE TABLESPACE TS_SCHEDULING_APPOINTMENTS;
ALTER TABLE TBL_VISITS MOVE TABLESPACE TS_SCHEDULING_APPOINTMENTS;
ALTER TABLE TBL_CANCELLED_HISTORIES MOVE TABLESPACE TS_SCHEDULING_APPOINTMENTS;