-- TBL_TECHNICAL_FILES
CREATE INDEX IDX_TEF_HISTORY ON TBL_TECHNICAL_FILES(tef_history_crops_id) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;
CREATE INDEX IDX_TEF_CREATION_DATE ON TBL_TECHNICAL_FILES(tef_creation_date) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;

-- TBL_ENVIRONMENTALS_DATA
CREATE INDEX IDX_END_TECH_FILE ON TBL_ENVIRONMENTALS_DATA(end_technical_files_id) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;
CREATE INDEX IDX_END_DATE ON TBL_ENVIRONMENTALS_DATA(end_date) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;

-- TBL_LABORATORY_ANALYSIS
CREATE INDEX IDX_LAA_TECH_FILE ON TBL_LABORATORY_ANALYSIS(laa_technical_files_id) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;
CREATE INDEX IDX_LAA_ANALYSIS_DATE ON TBL_LABORATORY_ANALYSIS(laa_analysis_date) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;

-- TBL_ANOTATIONS
CREATE INDEX IDX_ANO_TECH_FILE ON TBL_ANOTATIONS(ano_technical_files_id) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;
CREATE INDEX IDX_ANO_DATE ON TBL_ANOTATIONS(ano_date) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;
CREATE INDEX IDX_ANO_TITLE ON TBL_ANOTATIONS(ano_title) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;

-- TBL_WATER_SOURCES
CREATE INDEX IDX_WAS_TYPE ON TBL_WATER_SOURCES(was_type) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;
CREATE INDEX IDX_WAS_QUALITY ON TBL_WATER_SOURCES(was_quality) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;
CREATE INDEX IDX_WAS_QUANTITY ON TBL_WATER_SOURCES(was_quantity) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;

-- TBL_SOILS
CREATE INDEX IDX_SOI_NAME ON TBL_SOILS(soi_name) TABLESPACE TS_TECHNICAL_ENVIRONMENTAL;