CREATE TABLESPACE ts_catalogs
DATAFILE 'ts_catalogs.dbf' SIZE 100M
AUTOEXTEND ON NEXT 50M MAXSIZE 1G;

ALTER TABLE TBL_SPECIALITIES MOVE TABLESPACE TS_CATALOGS;
ALTER TABLE TBL_CERTFICATIONS MOVE TABLESPACE TS_CATALOGS;
ALTER TABLE TBL_COM_X_SPE MOVE TABLESPACE TS_CATALOGS;
ALTER TABLE TBL_CON_X_COM MOVE TABLESPACE TS_CATALOGS;
ALTER TABLE TBL_CRO_X_CRT MOVE TABLESPACE TS_CATALOGS;
ALTER TABLE TBL_PER_X_CON MOVE TABLESPACE TS_CATALOGS;
ALTER TABLE TBL_TEF_X_CER MOVE TABLESPACE TS_CATALOGS;
ALTER TABLE TBL_TEF_X_FAR MOVE TABLESPACE TS_CATALOGS;