PROMPT 
PROMPT ==================== FASE 5: LOGBOOKS ====================

PROMPT 6.1 Logbook: AGRONOMIC_VISITS...
@&BASE_PATH/security/logbooks/agronomic_visits/logook.sql

PROMPT 6.2 Logbook: AGRONOMIST_CHANGES...
@&BASE_PATH/security/logbooks/agronomist_changes/logbook.sql

PROMPT 6.3 Logbook: APPLIED_TREATMENTS...
@&BASE_PATH/security/logbooks/applied_treatments/logbook.sql

PROMPT 6.4 Logbook: AVAILABILITY_CHANGES...
@&BASE_PATH/security/logbooks/availability_changes/logbook.sql

PROMPT 6.5 Logbook: CROP_HISTORY...
@&BASE_PATH/security/logbooks/crop_history/logbook.sql

PROMPT 6.6 Logbook: DATA_MODIFICATIONS...
@&BASE_PATH/security/logbooks/data_modifications/logbook.sql

PROMPT 6.7 Logbook: ENCRYPTED_ROLE...
@&BASE_PATH/security/logbooks/encryted_role/logbook.sql

PROMPT 6.8 Logbook: FIELD_INSPECTIONS...
@&BASE_PATH/security/logbooks/field_inspections/logbook.sql

PROMPT 6.9 Logbook: LABORATORY_ANALYSIS...
@&BASE_PATH/security/logbooks/laboratory_analysis/logbook.sql

PROMPT 6.10 Logbook: SYSTEM_ERRORS...
@&BASE_PATH/security/logbooks/system_errors/logbook.sql

PROMPT 6.11 Logbook: FINANCE (Principal)...
@&BASE_PATH/security/logbooks/finance/logbook.sql

PROMPT 6.12 Logbook: FINANCE/ACCOUNT_PAYMENTS...
@&BASE_PATH/security/logbooks/finance/account_payments/logbook.sql

PROMPT 6.13 Logbook: FINANCE/AGRONOMIST...
@&BASE_PATH/security/logbooks/finance/agronomist/logbook.sql

PROMPT 6.14 Logbook: FINANCE/COMISSIONS...
@&BASE_PATH/security/logbooks/finance/comissions/logbook.sql

PROMPT 6.15 Logbook: FINANCE/SALARY_CHANGES...
@&BASE_PATH/security/logbooks/finance/salary_changes/logbook.sql

PROMPT 6.16 Logbook: FINANCE/SPECIALITY_PRICING...
@&BASE_PATH/security/logbooks/finance/speciality_pricing/logbook.sql