PROMPT 
PROMPT ==================== FASE 7: TRIGGERS ====================

PROMPT 7.1 Trigger: AGRONOMIC_VISITS...
@&BASE_PATH/security/logbooks/agronomic_visits/trigger.sql

PROMPT 7.2 Trigger: AGRONOMIST_CHANGES...
@&BASE_PATH/security/logbooks/agronomist_changes/trigger.sql

PROMPT 7.3 Trigger: APPLIED_TREATMENTS...
@&BASE_PATH/security/logbooks/applied_treatments/trigger.sql

PROMPT 7.4 Trigger: AVAILABILITY_CHANGES...
@&BASE_PATH/security/logbooks/availability_changes/trigger.sql

PROMPT 7.5 Trigger: CROP_HISTORY...
@&BASE_PATH/security/logbooks/crop_history/trigger.sql

PROMPT 7.6 Trigger: DATA_MODIFICATIONS...
@&BASE_PATH/security/logbooks/data_modifications/trigger.sql


PROMPT 7.8 Trigger: FIELD_INSPECTIONS...
@&BASE_PATH/security/logbooks/field_inspections/trigger.sql

PROMPT 7.9 Trigger: LABORATORY_ANALYSIS...
@&BASE_PATH/security/logbooks/laboratory_analysis/trigger.sql

PROMPT 7.10 Trigger: SYSTEM_ERRORS...
@&BASE_PATH/security/logbooks/system_errors/trigger.sql

PROMPT 7.11 Trigger: FINANCE/ACCOUNT_PAYMENTS...
@&BASE_PATH/security/logbooks/finance/account_payments/trigger.sql

PROMPT 7.12 Trigger: FINANCE/AGRONOMIST...
@&BASE_PATH/security/logbooks/finance/agronomist/trigger.sql

PROMPT 7.13 Trigger: FINANCE/COMISSIONS...
@&BASE_PATH/security/logbooks/finance/comissions/trigger.sql

PROMPT 7.14 Trigger: FINANCE/SALARY_CHANGES...
@&BASE_PATH/security/logbooks/finance/salary_changes/trigger.sql

PROMPT 7.15 Trigger: FINANCE/SPECIALITY_PRICING...
@&BASE_PATH/security/logbooks/finance/speciality_pricing/trigger.sql