PROMPT 
PROMPT ==================== FASE 9: JOBS PROGRAMADOS ====================

PROMPT 9.1 Jobs Diarios...
PROMPT 9.1.1 Verificación Tablespace...
@&BASE_PATH/jobs/daily/verify_tablespace_usage.sql

PROMPT 9.1.2 Verificación de Objetos Inválidos...
@&BASE_PATH/jobs/daily/verify_check_invalid_objects.sql

PROMPT 9.1.3 Verificación de Índices Corruptos...
@&BASE_PATH/jobs/daily/verify_corrupted_indexes.sql

PROMPT 9.1.4 Verificación de Cuentas Vencidas...
@&BASE_PATH/jobs/daily/verify_overdue_accounts.sql

PROMPT 9.1.5 Verificación de Visitas Técnicas...
@&BASE_PATH/jobs/daily/verify_technical_visits.sql

PROMPT 9.2 Jobs Mensuales...
PROMPT 9.2.1 Eliminación de Logs Antiguos...
@&BASE_PATH/jobs/mothly/delete_old_logs.sql

PROMPT 9.2.2 Verificación Reporte de Ingresos Mensuales...
@&BASE_PATH/jobs/mothly/verify_monthly_income_report.sql

PROMPT 9.3 Jobs Semestrales...
PROMPT 9.3.1 Reporte Semestral de Plagas y Enfermedades...
@&BASE_PATH/jobs/semester/semestral_pests_diseases_report.sql

PROMPT 9.3.2 Verificación Reporte Semestral de Productores...
@&BASE_PATH/jobs/semester/verify_semestral_producer_report.sql