-- Configuración SQL*Plus para ejecución limpia
SET ECHO OFF
SET FEEDBACK ON
SET TIMING OFF
SET VERIFY OFF
SET HEADING ON
SET PAGESIZE 50
SET LINESIZE 200
SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE ON
WHENEVER SQLERROR CONTINUE

-- Formato de columnas para fechas
COLUMN START_DATE FORMAT A10
COLUMN START_TIME FORMAT A8
COLUMN END_DATE FORMAT A10
COLUMN END_TIME FORMAT A8