-- Configuración SQL*Plus para ejecución limpia
SET ECHO OFF
SET FEEDBACK ON
SET TIMING OFF
SET VERIFY OFF
SET HEADING ON
SET PAGESIZE 50
SET LINESIZE 200
SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE ON