CREATE TABLE LOG_AVAILABILITY_CHANGES (
    log_id NUMBER PRIMARY KEY,
    ava_id NUMBER,
    previous_status VARCHAR2(20),
    new_status VARCHAR2(20),
    change_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    username VARCHAR2(50),
    reason VARCHAR2(200)
);

-- Sequence
CREATE SEQUENCE SEQ_LOG_AVAILABILITY START WITH 1 INCREMENT BY 1;